#ifndef SMTP_IM_GLOBAL_H
#define SMTP_IM_GLOBAL_H

#ifdef SMTP_MIME_LIBRARY_EN
#ifdef SMTP_MIME_LIBRARY
#define SMTP_MIME_EXPORT Q_DECL_EXPORT
#else
#define SMTP_MIME_EXPORT Q_DECL_IMPORT
#endif // SMTP_MIME_LIBRARY
#else
#define SMTP_MIME_EXPORT
#endif // SMTP_MIME_LIBRARY_EN

#endif // SMTP_IM_GLOBAL_H
